### ISSUE TITLE
Qt5 QtQuick Controls TabView has black background

### ISSUE THREAD

**Issue by beojan** [luebking/virtuality#24]
The QtQuick Controls TabView displays with a black (or perhaps foreground text) background, and the tops of selected tabs cut off by the border.

This does not happen with other tab views (e.g. QWidget tabviews)

**Comment by luebking** [comment]
Do you happen to have a testcase application? ("Where did you spot this")

**Comment by beojan** [comment]
```[qml]
import QtQuick 2.4
import QtQuick.Controls 1.3
import QtQuick.Window 2.2
import QtQuick.Dialogs 1.2
import QtQuick.Layouts 1.0

ApplicationWindow {
    id: applicationWindow1
    title: qsTr("Hello World")
    width: 640
    height: 480

    TabView {
        anchors.fill: parent
        Tab {
            id: tab1
            title: "Tab 1"
        }

        Tab {
            id: tab2
            title: "Tab 2"
        }

        Tab {
            id: tab3
            title: "Tab 3"

        }
    }


}
```

**Comment by luebking** [comment]
Thanks, but I actually meant "real life", because I thought this might be some invalid memory painted ;-)

Anyway, what you saw is the tabbar (indeed foreground text color; only when inverting headers)
In the end, I had to disable tabbar inversion for the (likely) QML case, because it turned out, that the "weird" looks resulted not only from false data supply (the tabwidget tabbar size is reported to cover the entire tabwidget) but also the tabwidget content is not shifted down (so would underflow the tabbar)

In addition there's some painting transformation post the style painting (cannot be ::resetTransformation()), so I disabled the entire thing - QML tabbars cannot be inverted for now.

**Comment by beojan** [comment]
It seems this fix has broken the Qt4 version (i.e. it no longer builds on Qt4)
